// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_win_600_points = "CgkIrIWusoIMEAIQBA"; // <GPGSID>
        public const string leaderboard_high_scores = "CgkIrIWusoIMEAIQCg"; // <GPGSID>
        public const string achievement_win_400_points = "CgkIrIWusoIMEAIQAw"; // <GPGSID>
        public const string achievement_win_200_points = "CgkIrIWusoIMEAIQAQ"; // <GPGSID>
        public const string achievement_earn_600_coins = "CgkIrIWusoIMEAIQCA"; // <GPGSID>
        public const string achievement_earn_400_coins = "CgkIrIWusoIMEAIQBw"; // <GPGSID>
        public const string achievement_earn_300_coins = "CgkIrIWusoIMEAIQBg"; // <GPGSID>
        public const string achievement_win_300_points = "CgkIrIWusoIMEAIQAg"; // <GPGSID>
        public const string achievement_first_time = "CgkIrIWusoIMEAIQAA"; // <GPGSID>
        public const string achievement_earn_200_coins = "CgkIrIWusoIMEAIQBQ"; // <GPGSID>

}

